### ISSUE TITLE
Service Definition: Do we need to provide an 'id'

### ISSUE THREAD

**Issue by npearce** [npearce/n8-GHE_IaC_WebHook#20]
Did AS3 implement the 'autogeneration' of 'id' as part of build 34 release. Test this and, if so, remove 'id' values from example service definitions.

**Comment by kreynoldsf5** [comment]
In build 34 a declaration without an 'id' key will fail with the following response:

```
{
    "code": 500,
    "declarationFullId": ""
}
```

**Comment by npearce** [comment]
Thanks, Kevin. I got it in the AS3 backlog but hadn't yet tested if it made the release. Thanks for saving me the time!!! I'll keep this here, and open, in case the next release of AS3 is out before I release v0.2...
